### ISSUE TITLE
Link to "encrypted secrets" GitHub Docs

### ISSUE THREAD

**Issue by felipeelia** [10up/action-wordpress-plugin-asset-update#10]
This is the same (quite small) problem reported [here](https://github.com/10up/action-wordpress-plugin-deploy/issues/19).

**Describe the bug**

Probably GitHub has updated their docs and the `Secrets are set in your repository settings` link present on the README.md file points to the wrong page.

**Steps to Reproduce**

1. Go to repo's README.md
2. Click on `Secrets are set in your repository settings.`
3. The link points to the [Virtual environments for GitHub-hosted runners](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#creating-and-using-secrets-encrypted-variables) page but the related section isn't there anymore :(

**Expected behavior**

The link should point to [this new page](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).

**Comment by jeffpaul** [comment]
Thanks again @felipeelia, it's much appreciated!
