### ISSUE TITLE
Check warning: The "master" branch is no longer the default branch name for actions/checkout

### ISSUE THREAD

**Issue by tedmasterweb** [10up/action-wordpress-plugin-asset-update#22]
**Describe your question**

Given I have a single branch "master" and the action has been installed with the branch name set to "master" (it is set as "trunk" in the example)

When I update the readme and push my changes

Then I get the warning "The "master" branch is no longer the default branch name for actions/checkout" and the action does not seem to work (the changes to the readme are not pushed to the svn repo).

I've tried creating a branch named "trunk" but get the same result.

This is the line that seems to be failing:

![image](https://user-images.githubusercontent.com/99979/88479686-d5d01400-cf48-11ea-9b6c-eb4527407763.png)

I'm very new to github actions so I'm not really sure where to look to try and debug this.

Thanks in advance.

**Comment by tedmasterweb** [comment]
I just noticed at the end of the script, this:

`🛑 Other files have been modified; changes not deployed`

So, is this action run _only_ when the README or .wordpres-org folder has changes?

**Comment by jeffpaul** [comment]
@tedmasterweb as noted in the [README.md file](https://github.com/10up/action-wordpress-plugin-asset-update#readme) its not that it runs _only_ then, its more precisely that it will _only_ push readme/asset changes to SVN if they're the _only_ changes being made:
> This Action commits any readme and WordPress.org-specific assets changes in your specified branch to the WordPress.org plugin repository if no other changes have been made since the last deployment to WordPress.org.

**Comment by helen** [comment]
@tedmasterweb I think you are mixing several items here. To address the branch naming, the name references in the workflow file like `actions/checkout@v2` are for the actions, not your repository. The `actions/checkout` repository is giving you a warning that `master` is not their default branch and it may not work as expected; the same is true for this repository.

**Comment by tedmasterweb** [comment]
Thanks both. Yes, I'm definitely confusing things, but I think I follow now. I'm brand new to actions. So, as it is a warning and not an error, do I need to do anything? Thanks for the clarifications.

FWIW, I've got the action working as expected now. What I'm still struggling with, though, is related to standard WordPress repo stuff, e.g.: if I have some minor changes to the code, changing indentation, adding inline documentation, etc., _and_ I change the readme, but I don't create a new tag, none of the changes will be pushed to the Subversion repo because the deploy action only pushes on a new tag and this action only pushes if the readme and .wordpress-org are the only files that have changed.

Have I understood correctly?

**Comment by Preciousomonze** [comment]
>FWIW, I've got the action working as expected now. What I'm still struggling with, though, is related to standard WordPress repo stuff, e.g.: if I have some minor changes to the code, changing indentation, adding inline documentation, etc., and I change the readme, but I don't create a new tag, none of the changes will be pushed to the Subversion repo because the deploy action only pushes on a new tag and this action only pushes if the readme and .wordpress-org are the only files that have changed.
>Have I understood correctly?

This Action commits any readme and WordPress.org-specific assets changes in your specified branch to the WordPress.org plugin repository **if no other changes have been made since the last deployment to WordPress.org**. This is useful for updating things like screenshots or Tested up to separately from functional changes, **provided your Git branching methodology avoids changing anything else in the specified branch between functional releases**. It is highly recommended that **you use a stable branch where you only merge readme/asset commits** in between larger functional merges that only occur when preparing for a release (often implemented as trunk vs. develop).

i hope this helps @tedmasterweb .
I also had to read it so many times 😄 .
But i think @helen is in a better position to give a more straight forward answer.
Oh and thanks for this By the way, @helen , I am still spreading the word, cause quite a number of plugin devs on my end do not even know this exists, they're still crying about having to joggle with SVN 😆 .

**Comment by tedmasterweb** [comment]
(I think I've read this 10 times and I'm still trying to make sure I've understood - I've been doing this for almost 30 years and I still find it difficult sometimes)

Normally, main is my release branch and tagged when x number of branches have been merged onto it with new features. So, my workflow is:

1. Define a new release (normally in terms of related github issues, bugs or features)
2. Make a new branch for the new release
3. Develop the features of fix the bugs
4. Merge onto main
5. Tag main with the new release number

Then, if I have changes to assets or the readme, I make them right on main and push.

Question: Should I be using a "Stable tag" in README.md and if so, what should it be set to prior to tagging? And after tagging?

Asking because I know the other deploy script creates a new folder/tag in the Subversion repo and things seem to have gotten out of sync for me. I hope this question seems reasonable!

I assume the answer is: it should be set to the tag name and not change until you tag main again.

This seems odd, though, because if main (the default, a.k.a. trunk) is my release branch, I'm not required to add a Stable tag. I sure hope these questions help others that may be as confused as I've been.

I really love this action, btw, and am very grateful to you for creating it. It seems to be just the ticket!

**Comment by Preciousomonze** [comment]
> Question: Should I be using a "Stable tag" in README.md

Uses readme.txt by default as said here: "_README_NAME - defaults to readme.txt, customizable in case you use README.md instead, which is now quietly supported in the WordPress.org plugin repository_"
Sorry, as for the rest, i am also not certain, will wait for a better answer than mine 😅 
I am also in a similar situation, i updated my plugin version(new release: v.1.2.0) , but i forgot to update the stable tag to v1.2.0.
I keep getting this **issue** error.

**Comment by jeffpaul** [comment]
@tedmasterweb this comes directly from the [WordPress.org Plugin Readmes handbook page](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/):

> **Stable Tag** – The stable version of the plugin. This is not the version of WordPress, but the version of the plugin itself. Only use numbers and periods, and [SemVer formatting](https://semver.org/) is recommended.

So if you are NOT using a readme.txt file and you're sending README.md across to the WordPress.org repo then yes you should include the `Stable` tag in README.md.  This will ensure that the `Version` shown on the WordPress.org repo (e.g., for your [Identify Headings plugin](https://wordpress.org/plugins/identify-headings/)) will be accurate to the lastest tagged release on GitHub.  I would recommend updating that to match the version just prior to tagging the release on GitHub.

We have some recommendations on [Release Processes](https://10up.github.io/Open-Source-Best-Practices/releasing/#release-process) to follow as part of our [Open Source Best Practices](https://10up.github.io/Open-Source-Best-Practices/).  I'd recommend taking a look at the release processes we've shared there, see which applies most to you, edit it to meet your needs, and follow that for future releases.

**Comment by tedmasterweb** [comment]
Thanks for all of your help. I've added an example git workflow via [PR](https://github.com/10up/action-wordpress-plugin-asset-update/pull/23) to maybe help others going forward.
