### ISSUE TITLE
Support REAME.md with list headers

### ISSUE THREAD

**Issue by grappler** [10up/action-wordpress-plugin-asset-update#25]
**Describe the bug**
> Could not get stable tag from README.md

The stable tag in the README.md was  as `* Stable tag: 2.1.2`.

**Steps to Reproduce**

1. Create a README.md with a Markdown list for the headers.
2. Run deployment
3. See error "Could not get stable tag from README.md"

**Expected behavior**
Be able to get the stable tag regardless if it is a list or not.

**Additional context**

The code responsible:
https://github.com/10up/action-wordpress-plugin-asset-update/blob/78630c5a75476c993066e833e2de6f20a29be777/entrypoint.sh#L115_L118

By removing `^` in `grep -m 1 "^Stable tag:" "$TMP_DIR/$README_NAME"`  would fix the bug.

WordPress.org parses the headers as follows.
https://github.com/WordPress/wordpress.org/blob/master/wordpress.org/public_html/wp-content/plugins/plugin-directory/readme/class-parser.php#L235-L253

As a temp fix I have switched for a list to using line breaks with two trailing whitespaces.

**Comment by jeffpaul** [comment]
@grappler is your use case here that you don't have a readme.txt for your plugin and instead you only use a README.md (that also exists on WP.org SVN)?  If so, mind sharing a link to a sample README.md that's formed this way?

Also, if you're able to test/comment on #27 that'll help there as well... thanks!

**Comment by grappler** [comment]
> is your use case here that you don't have a readme.txt for your plugin and instead you only use a README.md (that also exists on WP.org SVN)?

Yes, that is correct.

> If so, mind sharing a link to a sample README.md that's formed this way?

I had to change the formatting so that I could deploy to WordPress.org. Here is the [commit](https://github.com/wearerequired/wp-team-list/commit/575a7763ce8be16d1a69b9d7d5860af31b897d12) that I changed the formating.

**Comment by stklcode** [comment]
> is your use case here that you don't have a readme.txt for your plugin and instead you only use a README.md (that also exists on WP.org SVN)?

Same for me. For example this project has a single _README.md_ that is slightly modified during deployment (remove first lines with badges): [stklcode/statify-blacklist](https://github.com/stklcode/statify-blacklist)
Just recently migrated from a custom _Robo_ task to this GH action, so the run on [e794758](https://github.com/stklcode/statify-blacklist/commit/e794758d77cf9e1dbfd557c7603c4216b386520f) failed to update the 1.6.0 tag.

Other projects I contributed have similar issues, e.g. [Statify](https://github.com/pluginkollektiv/statify/blob/1cd194aa1b9622968b31d75547a2d6774daf5f48/readme.txt) (separate _readme.txt_, but with list formatting) or [AntiVirus](https://github.com/pluginkollektiv/antivirus/blob/b9c9afd19be2a94460a5c25345ba25d79b25f4a2/README.md) (single, unmodified _README.MD_)
