### ISSUE TITLE
SLUG not overwritten?

### ISSUE THREAD

**Issue by vyskoczilova** [10up/action-wordpress-plugin-asset-update#26]
**Describe the bug**

We wanted to deploy just a tiny change in readme.txt with this action, but it seems that the SLUG secret is not taken into account (or at least in our case). It was the first test in our (private) repo, but It should work like this, right?

**Steps to Reproduce**

1. Use Github repo with a different name than the slug on WP.org
2. Push to `trunk` branch
3. Step "WordPress.org plugin asset/readme update" should fail:
![image](https://user-images.githubusercontent.com/3611726/110647109-d6f04180-81b7-11eb-942f-7c84d4a9b568.png)

**Expected behavior**
Use SLUG from secrets.

**Additional context**
I'm happy to debug further (but I don't have access to the repository settings so it's a bit complicated). Thanks a lot in advance! (And really thanks for both WP.org related actions, they work like charm on my other projects)

**Comment by jeffpaul** [comment]
@vyskoczilova I'm not seeing a plugin on WordPress.org with the slug of `newsplugin-wp`, but I do see one with the slug of `newsplugin`.  Are you certain you have (1) the correct slug in your YML file and (2) the SVN username and password are correct and has commit access to the WP.org SVN repo?

**Comment by vyskoczilova** [comment]
Hi, 

we have a `SLUG` with `newsplugin` as a secret in Github & and we use this setup: https://github.com/10up/action-wordpress-plugin-asset-update#example-workflow-file but now when I know where you're heading to, we're missing that line, right?

```
SLUG: ${{ secrets.SLUG }}
```

Sorry for that, I'm not used to GitHub actions and I haven't thought that it won't take secret !== ENV value or something like that by default.

**Comment by jeffpaul** [comment]
@vyskoczilova you don't need to keep the slug in a secret, you can include that as plaintext in your YML, see the example here from one of our other GitHub Actions: https://github.com/10up/action-wordpress-plugin-deploy#deploy-on-pushing-a-new-tag

**Comment by vyskoczilova** [comment]
Good point, it's true. Thanks a lot for your help.
