### ISSUE TITLE
Best workflow

### ISSUE THREAD

**Issue by janw-me** [10up/action-wordpress-plugin-asset-update#28]
Hello,

I'm using this action and the [plugin deploy](https://github.com/10up/action-wordpress-plugin-deploy) action.
Today I had a small bug fix I did the following steps.

1. Changed a few php files, updated version numbers in the plugin file and in the `readme.txt`
2. Committed this to the `dev` branch and pushed.
3. merged `dev` to `main` branch
4. This action runs and errors on [Other files have been modified](https://github.com/10up/action-wordpress-plugin-asset-update/issues/24)
5. I create a release and create a tag.
6. The plugin deploy action runs and deploys to WordPress.org
7. All is well in the lands.

Is this the intended workflow? Is there a way to do this process without triggering the error in step 4.
There isn't a real problem but the failed pipeline insinuates that something went wrong, that there is a real error.

Maybe I'm missing something, I'm trying to understand how this should work.

**Comment by dinhtungdu** [comment]
> Is this the intended workflow?

Hi @janw-me Yes, see this from the `readme.md`:

> This Action commits any readme and WordPress.org-specific assets changes in your specified branch to the WordPress.org plugin repository if no other changes have been made since the last deployment to WordPress.org.

This behavior ensures you don't deploy new versions of the readme without respective changes deployed to wordpress.org.

**Comment by janw-me** [comment]
I understand, Still it's a bit annoying to have "failed" actions when it's intended behaviour.
