### ISSUE TITLE
Error on deployment: Other files have been modified; changes not deployed

### ISSUE THREAD

**Issue by helgatheviking** [10up/action-wordpress-plugin-asset-update#29]
**Describe your question**
I pushed this commit https://github.com/helgatheviking/Nav-Menu-Roles/commit/95d6442683ae1fd3fe4ebe700378e5b9314ee608 to my `readme.txt` file which triggered the update assets action.

However, it is failing with the message that "Other files have been modified; changes not deployed". 

The job failure shows some others as modified and I am not why?
https://github.com/helgatheviking/Nav-Menu-Roles/runs/2382611855?check_suite_focus=true

**Comment by dinhtungdu** [comment]
Hi @helgatheviking,

There are some commits in the master branch that haven't tagged yet, which means those changes haven't been deployed to wordpress.org. That's why you got that error message.

See this: https://github.com/helgatheviking/Nav-Menu-Roles/compare/25381e281d...95d6442
