### ISSUE TITLE
Failure on action run

### ISSUE THREAD

**Issue by ahdbjjhdibdvuil** [10up/action-wordpress-plugin-asset-update#33]
**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Additional context**

**Comment by ahdbjjhdibdvuil** [comment]
Note

Not getting “Hello world” but some crazy error about “can’t open file” or “No such file or directory?” Your command line might not be running in the directory that you saved the file in. You can change the working directory of your current command line with the cd command, which stands for “change directory”. On Windows, you might want something like:

**Comment by jeffpaul** [comment]
@ahdbjjhdibdvuil can you please provide a link to your failing run so we can help triage what might be wrong for you?

**Comment by dragunoff** [comment]
I got this error when trying to use the action: 
```
➤ Copying files...
rsync: change_dir "/home/runner/work/wp-stage-switcher/wp-stage-switcher/.wordpress-org" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
Error: Process completed with exit code 23.
```
Here's the failed run: https://github.com/dragunoff/wp-stage-switcher/runs/4938006285

I'm using the `develop` branch with `IGNORE_OTHER_FILES: true`.

**Comment by jeffpaul** [comment]
@dragunoff I'd definitely recommend changing from `develop` to `stable` here: https://github.com/dragunoff/wp-stage-switcher/blob/15241ee3411ce55e172560aebaa8148e6cc5ec65/.github/workflows/update-readme-assets.yml#L13.  You're otherwise living a bit dangerously there.

**Comment by jeffpaul** [comment]
@dragunoff you'll also need to add the following to your https://github.com/dragunoff/wp-stage-switcher/blob/main/.github/workflows/update-readme-assets.yml file:
> ASSETS_DIR: .wordpress.org  (this might need quotes around it, not fully certain there)

...since yours is not matching the expected ".wordpress-org" format.

**Comment by dragunoff** [comment]
Oh, so it was just a typo :smile: it works now.
@jeffpaul Thanks!
