### ISSUE TITLE
Confusing workflow/documentation

### ISSUE THREAD

**Issue by UVLabs** [10up/action-wordpress-plugin-asset-update#50]
Not sure if my brain is just tired or the documentation is confusing. I've read it over several times but still not comfortable implementing this action out of fear that ill mess something up in my current deploy workflow.

Here's my workflow:

- Code, code, code
- Push all that code to `development` branch (rinse and repeat)
- **It's release day, lets make a release** -> Merge `development` branch into my `master` branch.
- My needed initial actions take effect and do what they have to and cancel the deployment if needed. 
- If no issues, the next action called is https://github.com/10up/action-wordpress-plugin-deploy which syncs SVN.

My situation:

- I updated some screenshots and the readme...
- What now?

**Question 1:** _Do I push them to `development` branch and then merge into `master` and call it a day? So this action would see that it's only those assets updated and it would sync SVN with just those screenshot and readme changes while leaving all other PHP/Folders untouched?_

----

Here's the spanner in the workflow...

When updating the readme and screenshots, I would NOT want https://github.com/10up/action-wordpress-plugin-deploy to be ran.

I would just want to maybe be able to push to a special branch called `interim` (or something else) where I can push ONLY assets (`.wordpress-org`) and `readme.txt` that would need to be updated on SVN until I actually make a release that would contain those _interim_ changes and any other changes i did to PHP etc.

So say I make some changes to my assets, I don't plan to release a new version of the plugin yet, I just want to update those asset files and the readme and have them sync on SVN.

**Question 2:** Is that possible?

----

I think the part of the documention that confuses me is:

> As `main` is our "release" branch, changes to anything other than the `readme.txt` and `.wordpress-org` can only be made live by tagging `main`.
If, however, you need to update the readme.txt or assets folder (`.wordpress-org`) for any reason, you should do that directly on `main` and then push your changes. This action will verify that only the `readme.txt` and `.wordpress-org` contain changes and if so, will push them directly to `trunk` on the WordPress svn repository.

In the wording you're saying main shouldn't be touched for anything other than true releases...yet you're saying push those asset and readme.txt changes to main...

**Comment by jeffpaul** [comment]
@UVLabs ...

> Question 1: Do I push them to development branch and then merge into master and call it a day? So this action would see that it's only those assets updated and it would sync SVN with just those screenshot and readme changes while leaving all other PHP/Folders untouched?

Yes, assuming you're using a workflow file relatively similar to https://github.com/10up/action-wordpress-plugin-asset-update#example-workflow-file and swapping `master` in for `trunk` (as our example assumes `trunk` in place of your usage of `master`).  Assuming you've merged no other changes to `master`, the action will pick up the readme and/or asset changes and push those to SVN without tagging a new version on SVN.

> When updating the readme and screenshots, I would NOT want https://github.com/10up/action-wordpress-plugin-deploy to be ran.

As long as you're using a workflow file relatively similar to https://github.com/10up/action-wordpress-plugin-deploy#deploy-on-pushing-a-new-tag or https://github.com/10up/action-wordpress-plugin-deploy#deploy-on-publishing-a-new-release-and-attach-a-zip-file-to-the-release, then those deploy actions will ONLY trigger when you tag a version or publish a release on GitHub (respectively).

> Question 2: Is that possible?

Yes, though I would not worry about the `interim` branch in your example as you can push stray readme/asset update changes to `master` and this action will pick those up and push to SVN (again, assuming no other changes are pushed to `master`).  When you're ready to release a new plugin version and push to SVN, then tagging/publishing a release will trigger the deploy action.

> In the wording you're saying main shouldn't be touched for anything other than true releases...yet you're saying push those asset and readme.txt changes to main...

I'm not getting how you infer this from our text, could you perhaps more precisely highlight where in the text you're getting confused?
