### ISSUE TITLE
Replace deprecated set-output command

### ISSUE THREAD

**Issue by jeffpaul** [10up/action-wordpress-plugin-asset-update#51]
**Is your enhancement related to a problem? Please describe.**
Let's replicate the update in https://github.com/10up/action-wordpress-plugin-deploy/pull/108 here.

**Describe the solution you'd like**

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by Preciousomonze** [comment]
Let me see if i can hop on this.
