### ISSUE TITLE
Deploy.sh not found

### ISSUE THREAD

**Issue by MuhammadFaizanHaidar1** [10up/action-wordpress-plugin-asset-update#59]
**Describe the bug**
home/runner/work/_actions/10up/action-wordpress-plugin-asset-update/stable/deploy.sh: line 48: svn: command not found
I am using above action to push to trunk of my plugin. But getting error mentioned above.

**Steps to Reproduce**

Can push to trunk

**Expected behavior**
It should push to svn repository trunk folder.

**Additional context**

Link to the action
https://github.com/inspry/agency-toolkit/actions/runs/11327924745/job/31500011874

**Comment by jeffpaul** [comment]
@MuhammadFaizanHaidar1 seems that repo is private so I'm not able to review the action run to help triage.  Could you copy out the details and share here?

**Comment by MuhammadFaizanHaidar1** [comment]
Hi @jeffpaul sorry for getting back to you so late. But I resolved this issue by first installing svn in my action.
Thanks!
