### ISSUE TITLE
Readme change could not update the readme from stable tag.

### ISSUE THREAD

**Issue by Nikschavan** [10up/action-wordpress-plugin-asset-update#7]
From the logs of the action run, it looks like grep could not find stable tag from the readme.txt - 
```
grep: /readme.txt: No such file or directory
Could not get stable tag from readme.txt
```

Here is the [link](https://github.com/Nikschavan/bb-header-footer/commit/4f091ea58074529ac0859edf93fa2fb68fbee5ca/checks#step:4:79) to the action log.
And this is the [actual commit](https://plugins.trac.wordpress.org/changeset/2155272/bb-header-footer) that was made by the action, As you can see the change was only made in the trunk and not in the stable tag.

The same thing happened for another plugin, here is it's [action log](https://github.com/brainstormforce/read-meter/commit/2f04b1a93ecf3e22d82290f05553053100d25218/checks#step:4:87)
And a [link to commit](https://plugins.trac.wordpress.org/changeset/2153968) that was made from the action.

Here is a link to the [action yml file](https://github.com/Nikschavan/bb-header-footer/blob/master/.github/workflows/push-asset-readme-update.yml.yml) it is taken from readme of this repo and without any modifications.

Any ideas if I am missing anything?

**Comment by helen** [comment]
Hi @Nikschavan - I'm so sorry that I missed this notification before. Looking at your PR in #8, I missed that we were skipping the `TMP_DIR` entirely when I made the change for supporting `.distignore`. The change here needs to be split along the code path so that it still looks in `TMP_DIR` if not using `.distignore`.

**Comment by Nikschavan** [comment]
Thank you for the feedback @helen, I have updated the PR #8 as per the feedback, do let me know if there is anything else needed for this.
